# Generated by Django 6.0.3 on 2026-03-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_verificationcoderequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcoderequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('sent', 'Sent (Legacy)'), ('failed', 'Failed (Legacy)')], default='pending', max_length=10),
        ),
    ]
