# Generated by Django 6.0.3 on 2026-03-07 13:18

import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_verificationcoderequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=management.models.default_verification_expiry),
        ),
    ]
