# Generated by Django 6.0.3 on 2026-03-07 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_fee_created_at_auditlog_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resident',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='management__date_c8f161_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status'], name='management__status_e50db7_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['resident', 'date'], name='management__residen_ceef6e_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='management__action_3058f1_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='management__created_50f0e1_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['target_type', 'target_id'], name='management__target__00927b_idx'),
        ),
        migrations.AddIndex(
            model_name='fee',
            index=models.Index(fields=['paid'], name='management__paid_9200d8_idx'),
        ),
        migrations.AddIndex(
            model_name='fee',
            index=models.Index(fields=['date_paid'], name='management__date_pa_1bb809_idx'),
        ),
        migrations.AddIndex(
            model_name='fee',
            index=models.Index(fields=['created_at'], name='management__created_36f729_idx'),
        ),
        migrations.AddIndex(
            model_name='fee',
            index=models.Index(fields=['resident', 'paid'], name='management__residen_c83fc4_idx'),
        ),
        migrations.AddIndex(
            model_name='loginactivity',
            index=models.Index(fields=['login_at'], name='management__login_a_86873d_idx'),
        ),
        migrations.AddIndex(
            model_name='loginactivity',
            index=models.Index(fields=['user', 'login_at'], name='management__user_id_38b2a6_idx'),
        ),
        migrations.AddIndex(
            model_name='purokclearance',
            index=models.Index(fields=['date_issued'], name='management__date_is_7e8686_idx'),
        ),
        migrations.AddIndex(
            model_name='purokclearance',
            index=models.Index(fields=['resident', 'date_issued'], name='management__residen_a6cbd6_idx'),
        ),
        migrations.AddIndex(
            model_name='resident',
            index=models.Index(fields=['purok'], name='management__purok_15eef4_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcoderequest',
            index=models.Index(fields=['status'], name='management__status_99b496_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcoderequest',
            index=models.Index(fields=['requested_at'], name='management__request_427502_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcoderequest',
            index=models.Index(fields=['email'], name='management__email_be5e71_idx'),
        ),
    ]
