# Generated by Django 6.0.3 on 2026-03-08 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_resident_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('approve_user', 'Approve User'), ('create_code', 'Create Login Code'), ('mark_fee_paid', 'Mark Fee Paid'), ('issue_clearance', 'Issue Clearance')], max_length=40),
        ),
        migrations.AlterField(
            model_name='purokclearance',
            name='clearance_type',
            field=models.CharField(choices=[('Barangay', 'Purok Clearance'), ('Business', 'Purok Clearance')], max_length=50),
        ),
    ]
