# Generated by Django 6.0.3 on 2026-04-23 14:03

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def dedupe_rows_before_constraints(apps, schema_editor):
    Attendance = apps.get_model("management", "Attendance")
    PaymentTransaction = apps.get_model("management", "PaymentTransaction")

    duplicate_attendance_groups = (
        Attendance.objects.values("resident_id", "date", "attendance_type")
        .annotate(total=Count("id"))
        .filter(total__gt=1)
    )
    for group in duplicate_attendance_groups:
        duplicate_ids = list(
            Attendance.objects.filter(
                resident_id=group["resident_id"],
                date=group["date"],
                attendance_type=group["attendance_type"],
            )
            .order_by("id")
            .values_list("id", flat=True)
        )
        Attendance.objects.filter(id__in=duplicate_ids[1:]).delete()

    duplicate_pending_payment_groups = (
        PaymentTransaction.objects.filter(status="pending")
        .values("fee_id")
        .annotate(total=Count("id"))
        .filter(total__gt=1)
    )
    for group in duplicate_pending_payment_groups:
        duplicate_ids = list(
            PaymentTransaction.objects.filter(fee_id=group["fee_id"], status="pending")
            .order_by("id")
            .values_list("id", flat=True)
        )
        PaymentTransaction.objects.filter(id__in=duplicate_ids[1:]).delete()


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_remove_barangay_clearancetype_again'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendance',
            new_name='management__attenda_8f52a7_idx',
            old_name='management_a_attenda_a13c6c_idx',
        ),
        migrations.RunPython(dedupe_rows_before_constraints, reverse_code=noop_reverse),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('resident', 'date', 'attendance_type'), name='unique_attendance_per_resident_date_type'),
        ),
        migrations.AddConstraint(
            model_name='fee',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='fee_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount_sent__gte', 0)), name='payment_amount_sent_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('fee',), name='unique_pending_payment_per_fee'),
        ),
    ]
