# Generated by Django 6.0.3 on 2026-04-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_rename_management_a_attenda_a13c6c_idx_management__attenda_8f52a7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
