# Generated by Django 6.0.3 on 2026-04-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='resident',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
