# Generated by Django 6.0.3 on 2026-04-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_resident_address_resident_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='place_of_birth',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
