# Generated by Django 6.0.3 on 2026-04-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_resident_place_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='resident',
            name='household_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
