# Generated by Django 6.0.3 on 2026-04-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0023_resident_gender_resident_household_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feetype",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
